repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8 --extend-ignore E712,E203
        language: system
        types: [python]
        exclude: '^app/core/db/migrations/|^app/core/middleware/db_session_context.py$'