name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install .

    - name: Install pytest
      run: pip install pytest pytest-cov pytest-asyncio pytest-mock
  
    - name: Run Unit Tests
      run: make test

    - name: Build Docker Compose
      run: make build
